# Generated by Django 4.2.2 on 2023-07-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=250)),
                ('user_phone_number', models.IntegerField()),
                ('user_entrolment_id', models.IntegerField()),
                ('user_specialization', models.CharField(max_length=250)),
                ('user_address', models.CharField(max_length=300)),
            ],
        ),
    ]
