# Generated by Django 4.2.2 on 2023-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_password',
            field=models.CharField(default='siju', max_length=25),
        ),
    ]
